spring:
  cloud:
    stream:
      function:
        definition: processDropoffRideAverages
      bindings:
        processDropoffRideAverages-out-0:
          destination: test/taxi/yourname2/nyc/v1/stats/dropoff/avg
        processDropoffRideAverages-in-0:
          destination: test/taxi/RideDropoffProcessorQueue
      solace:
        bindings:
          processDropoffRideAverages-in-0:
            consumer:
              queueAdditionalSubscriptions: 'taxi/nyc/v1/dropoff/>'
solace:
  java:
    host: tcp://mr-d8f4yze27kt.messaging.solace.cloud:55555
    msgVpn: cto-demo-virginia-azure
    clientUsername: public-taxi-user
    clientPassword: iliketaxis
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'

